### ISSUE TITLE
Better Multishot 2.0.0 does not work with RPGStats.

### ISSUE THREAD

**Issue by HyperSoop** [OffsetMonkey538/Random-Minecraft-Ideas#6]
Another apply error, this time on the server. https://modrinth.com/mod/rpgstats
```[05:48:15] [main/ERROR]: Mixin apply for mod rpgstats failed rpgstats.mixins.json:BowAccuracyMixin from mod rpgstats -> net.minecraft.class_1753: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_1753::rpgstats$changeAccuracy with priority 1000 cannot inject into net/minecraft/class_1753::method_7840(Lnet/minecraft/class_1799;Lnet/minecraft/class_1937;Lnet/minecraft/class_1309;I)V merged by io.github.offsetmonkey538.bettermultishot.mixin.item.BowItemMixin with priority 1000 [PREINJECT Applicator Phase -> rpgstats.mixins.json:BowAccuracyMixin from mod rpgstats -> Prepare Injections ->  -> handler$cke000$rpgstats$changeAccuracy(Lnet/minecraft/class_1799;Lnet/minecraft/class_1937;Lnet/minecraft/class_1309;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1657;ZLnet/minecraft/class_1799;IFZLnet/minecraft/class_1744;Lnet/minecraft/class_1665;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_1753::rpgstats$changeAccuracy with priority 1000 cannot inject into net/minecraft/class_1753::method_7840(Lnet/minecraft/class_1799;Lnet/minecraft/class_1937;Lnet/minecraft/class_1309;I)V merged by io.github.offsetmonkey538.bettermultishot.mixin.item.BowItemMixin with priority 1000 [PREINJECT Applicator Phase -> rpgstats.mixins.json:BowAccuracyMixin from mod rpgstats -> Prepare Injections ->  -> handler$cke000$rpgstats$changeAccuracy(Lnet/minecraft/class_1799;Lnet/minecraft/class_1937;Lnet/minecraft/class_1309;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1657;ZLnet/minecraft/class_1799;IFZLnet/minecraft/class_1744;Lnet/minecraft/class_1665;)V -> Prepare]
        at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77) ~[libjf-unsafe-v0-3.1.0-74f4f23f5e880260.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.minecraft.class_1792.method_7867(class_1792.java:74) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.method_8389(class_2248.java:554) ~[server-intermediary.jar:?]
        at net.minecraft.class_7143$class_7144.method_41583(class_7143.java:60) ~[server-intermediary.jar:?]
        at net.minecraft.class_7143$class_7144.method_41581(class_7143.java:66) ~[server-intermediary.jar:?]
        at net.minecraft.class_7143.method_41579(class_7143.java:199) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) [?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:104) [server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:326) [server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:50) [server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:98) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-launch.jar:0.11.0]
[05:48:15] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-launch.jar:0.11.0]
Caused by: java.lang.ExceptionInInitializerError
        at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
        ... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1753 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.minecraft.class_1792.method_7867(class_1792.java:74) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.method_8389(class_2248.java:554) ~[server-intermediary.jar:?]
        at net.minecraft.class_7143$class_7144.method_41583(class_7143.java:60) ~[server-intermediary.jar:?]
        at net.minecraft.class_7143$class_7144.method_41581(class_7143.java:66) ~[server-intermediary.jar:?]
        at net.minecraft.class_7143.method_41579(class_7143.java:199) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
        ... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77) ~[libjf-unsafe-v0-3.1.0-74f4f23f5e880260.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.minecraft.class_1792.method_7867(class_1792.java:74) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.method_8389(class_2248.java:554) ~[server-intermediary.jar:?]
        at net.minecraft.class_7143$class_7144.method_41583(class_7143.java:60) ~[server-intermediary.jar:?]
        at net.minecraft.class_7143$class_7144.method_41581(class_7143.java:66) ~[server-intermediary.jar:?]
        at net.minecraft.class_7143.method_41579(class_7143.java:199) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
        ... 4 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [rpgstats.mixins.json:BowAccuracyMixin from mod rpgstats] from phase [DEFAULT] in config [rpgstats.mixins.json] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77) ~[libjf-unsafe-v0-3.1.0-74f4f23f5e880260.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.minecraft.class_1792.method_7867(class_1792.java:74) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.method_8389(class_2248.java:554) ~[server-intermediary.jar:?]
        at net.minecraft.class_7143$class_7144.method_41583(class_7143.java:60) ~[server-intermediary.jar:?]
        at net.minecraft.class_7143$class_7144.method_41581(class_7143.java:66) ~[server-intermediary.jar:?]
        at net.minecraft.class_7143.method_41579(class_7143.java:199) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
        ... 4 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on net/minecraft/class_1753::rpgstats$changeAccuracy with priority 1000 cannot inject into net/minecraft/class_1753::method_7840(Lnet/minecraft/class_1799;Lnet/minecraft/class_1937;Lnet/minecraft/class_1309;I)V merged by io.github.offsetmonkey538.bettermultishot.mixin.item.BowItemMixin with priority 1000 [PREINJECT Applicator Phase -> rpgstats.mixins.json:BowAccuracyMixin from mod rpgstats -> Prepare Injections ->  -> handler$cke000$rpgstats$changeAccuracy(Lnet/minecraft/class_1799;Lnet/minecraft/class_1937;Lnet/minecraft/class_1309;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1657;ZLnet/minecraft/class_1799;IFZLnet/minecraft/class_1744;Lnet/minecraft/class_1665;)V -> Prepare]
        at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1338) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
        at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77) ~[libjf-unsafe-v0-3.1.0-74f4f23f5e880260.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.minecraft.class_1792.method_7867(class_1792.java:74) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.method_8389(class_2248.java:554) ~[server-intermediary.jar:?]
        at net.minecraft.class_7143$class_7144.method_41583(class_7143.java:60) ~[server-intermediary.jar:?]
        at net.minecraft.class_7143$class_7144.method_41581(class_7143.java:66) ~[server-intermediary.jar:?]
        at net.minecraft.class_7143.method_41579(class_7143.java:199) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
        ... 4 more```

**Comment by OffsetMonkey538** [comment]
Thanks for the report! Will look into it when I get the time.

**Comment by OffsetMonkey538** [comment]
I have gotten it to work, RPGStats itself needed a change to make the accuracy thing actually work, that's done in SilverAndro/RPGStats#116.

**Comment by OffsetMonkey538** [comment]
more updates soon:tm:

**Comment by HyperSoop** [comment]
modrinth release for the fix please!

**Comment by OffsetMonkey538** [comment]
ah, yeah, forgot about that

**Comment by OffsetMonkey538** [comment]
https://modrinth.com/mod/bettermultishot/version/2.1.0%2B1.19.2

**Comment by HyperSoop** [comment]
i added this to my server at last and the client suffers way more than the server

throwing a multishot 255 snowball hung my client and the server was fine

**Comment by OffsetMonkey538** [comment]
Two questions:

1. *Why would you throw a multishot 255 snowball?*
2. Does it only happen with RPGStats installed?

**Comment by HyperSoop** [comment]
> Two questions:
> 
> 1. _Why would you throw a multishot 255 snowball?_
> 2. Does it only happen with RPGStats installed?

1. because why not
2. it's a client only thing, and that didn't have rpgstats

**Comment by OffsetMonkey538** [comment]
~~Could it be that the game has to render 511 snowballs?~~
Currently don't have time to test it myself and can't really think of why it would do that.

**Comment by HyperSoop** [comment]
you should not test this i put in that statement as a half joke

**Comment by OffsetMonkey538** [comment]
But I'm curio now
